language: c

install:
    - sudo apt-get install pkg-config lua5.2 liblua5.2-dev
    - git clone git://github.com/hcatlin/libsass.git
    - cd libsass
    - autoreconf -i
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - sudo ldconfig

script: make check USE_LIBTOOL=1

notifications:
    email: false
